global:
  name: SSI Alliance Interactive Landscape
  short_name: SSI-Alliance
  repo: SSIAssociation/ssia-landscape
  website: https://landscape.ssia.org
  short_domain: l.landscape.ssia.org
  company_url: https://www.ssia.org
  email: info@www.ssia.org
  self: https://www.crunchbase.com/organization/ssia
  meta:
    title: SSIA Interactive Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@PROJECTTWITTER'
    google_site_verification: null
    ms_validate: null
  membership: SSIA Members
  flags:
    gray_large_items: true
twitter:
  search: landscape.ssia.org
  url: https://landscape.ssia.org
  text: SSIA Landscape
relation:
  label: SSIA Relation
  url: ssia
  values:
    - id: hosted
      label: SSIA Projects
      children:
        - id: projects
          label: SSIA Projects
          prefix: ssia
          tag: Projects
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: SSIA Projects
          big_picture_color: rgb(24,54,114)
    - id: company
      label: PROJECTNAME Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: SSIA Member Products/Projects
      tag: PROJECTNAME Member
    - id: false
      label: Non-SSIA Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: SSIA
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: SSIA
    label: General Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>SSI Alliance Interactive Landscape</h1> The SSIA Landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads: null
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: SSIA Landscape
    fullscreen_header: See the interactive landscape at l.ssia.org
    elements:
      - type: HorizontalCategory
        category: Building Management Software
        rows: 4
        width: 300
        height: 150
        top: 10
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Cloud Computing
        rows: 4
        width: 300
        height: 150
        top: 10
        left: 330
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Data Transfer
        rows: 4
        width: 550
        height: 150
        top: 10
        left: 650
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Datacenter Construction
        rows: 4
        width: 1200
        height: 150
        top: 260
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Datacenter Cooling
        rows: 2
        width: 1200
        height: 150
        top: 430
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Datacenter Operations
        rows: 2
        width: 1200
        height: 150
        top: 600
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Fluids and Chemicals
        rows: 2
        width: 400
        height: 150
        top: 770
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: Silicon
        rows: 2
        width: 780
        height: 150
        top: 770
        left: 420
        color: rgb(103,66,18)
        fit_width: true
        is_large: true
      - type: HorizontalCategory
        category: SSIA Members
        rows: 2
        width: 400
        height: 150
        top: 970
        left: 0
        color: rgb(103,66,18)
        fit_width: true
        is_large: true

test:
  header: SSI Alliance Interactive Landscape
  section: Non-SSIA Member Products/Projects
  logo: intel.svg
prerender:
  members: /card-mode?category=open-mainframe-project-member-company&grouping=category&embed=yes&style=borderless
